# Generated by Django 2.2.3 on 2019-08-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t',
            name='modified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
